# Generated by Django 2.1.5 on 2019-01-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190124_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='shop.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('receive_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('return_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('due_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('total_amount', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ('bill_number',),
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='active_inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, related_name='sales', to='shop.Customer'),
        ),
        migrations.AddField(
            model_name='row',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='shop.Sale'),
        ),
        migrations.AddField(
            model_name='row',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, related_name='rows', to='shop.Unit'),
        ),
    ]
